# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a994c875e6c39a0a2d364bd57640bd5d0200d093735bcf22a4cef4cc3c6aafe4f1ea706441241858a814029acb42bd45468de9559af21ab119a805e173765bd2

test:
  secret_key_base: b2876b716ee474c4f4edcbae696af5c625af8ac41c6d8209ce6583f08d1db2332d899ccbb5b2a23f478300a1dd6fc2afdf3e4a8dcd651c79d58ecdf589060730

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
